services:
  DBP\API\LocationCheckInBundle\Service\LocationCheckInApi:
    public: false
    autowire: true

  DBP\API\LocationCheckInBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  DBP\API\LocationCheckInBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  DBP\API\LocationCheckInBundle\MessageHandler\LocationGuestCheckOutHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']
