services:
  Dbp\Relay\CheckinBundle\Service\CheckinApi:
    public: false
    autowire: true
    calls:
      - setCache: [ '@dbp.relay.checkin.cache.location' ]

  Dbp\Relay\CheckinBundle\Service\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\CheckinBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CheckinBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CheckinBundle\MessageHandler\GuestCheckOutHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']

  dbp.relay.checkin.cache.location:
    parent: cache.app
    tags:
      - { name: 'cache.pool', default_lifetime: 60 }
