services:
  Dbp\Relay\CheckinBundle\Service\CheckinApi:
    public: false
    autowire: true

  Dbp\Relay\CheckinBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CheckinBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\CheckinBundle\MessageHandler\GuestCheckOutHandler:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['messenger.message_handler']
