services:
  DBP\API\LocationCheckInBundle\Service\LocationCheckInApi:
    public: false
    autowire: true

  DBP\API\LocationCheckInBundle\DataPersister\:
    resource: '../../DataPersister'
    tags: ['api_platform.data_persister']
    autowire: true

  DBP\API\LocationCheckInBundle\DataProvider\CheckInPlaceItemDataProvider:
    tags: [{ name: 'api_platform.item_data_provider'}]
    autowire: true

  DBP\API\LocationCheckInBundle\DataProvider\CheckInPlaceCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true

  DBP\API\LocationCheckInBundle\DataProvider\LocationCheckInActionCollectionDataProvider:
    tags: [{ name: 'api_platform.collection_data_provider'}]
    autowire: true
